<?php

namespace Subapp\Sql\Render\Common\Represent\Condition;

use Subapp\Sql\Ast\Condition\IsNull as IsNullExpression;
use Subapp\Sql\Ast\NodeInterface;
use Subapp\Sql\Render\AbstractRepresent;
use Subapp\Sql\Render\RendererInterface;

/**
 * Class IsNull
 * @package Subapp\Sql\Render\Common\Represent\Condition
 */
class IsNull extends AbstractRepresent
{
    
    /**
     * @param NodeInterface|IsNullExpression $node
     * @param RendererInterface                    $renderer
     * @return string
     */
    public function getSql(NodeInterface $node, RendererInterface $renderer)
    {
        return sprintf('%s IS%sNULL',
            $renderer->render($node->getLeft()),
            ($node->isNot() ? ' NOT ' : ' '));
    }

    /**
     * @inheritDoc
     */
    public function toArray(NodeInterface $node, RendererInterface $renderer)
    {
        return parent::toArray($node, $renderer); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function toNode(array $values, RendererInterface $renderer)
    {
        parent::toNode($values, $renderer); // TODO: Change the autogenerated stub
    }


}