<?php

namespace Subapp\Sql\Converter\Common\Condition;

use Subapp\Sql\Ast\Condition\IsNull as IsNullNode;
use Subapp\Sql\Ast\NodeInterface;
use Subapp\Sql\Converter\AbstractConverter;
use Subapp\Sql\Converter\ProviderInterface;

/**
 * Class IsNull
 * @package Subapp\Sql\Converter\Common\Condition
 */
class IsNull extends AbstractConverter
{
    
    /**
     * @param NodeInterface|IsNullNode $node
     * @param ProviderInterface                    $provider
     * @return string
     */
    public function toSql(NodeInterface $node, ProviderInterface $provider)
    {
        return sprintf('%s IS%sNULL',
            $provider->toSql($node->getLeft()),
            ($node->isNot() ? ' NOT ' : ' '));
    }

    /**
     * @inheritDoc
     */
    public function toArray(NodeInterface $node, ProviderInterface $provider)
    {
        return parent::toArray($node, $provider); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function toNode(array $ast, ProviderInterface $provider)
    {
        parent::toNode($ast, $provider); // TODO: Change the autogenerated stub
    }


}